/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5e138553-8f90-48fe-ae96-34fa1116c9b0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XK5ttYDDs",
    "aws_user_pools_web_client_id": "e9m80o8ufjtl6bj1h6a6m1j09",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://xyh4v2bc3vbqzbzsomsaqm6gwm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5coaxdwlqfhxpfp6dhotfe7i5i",
    "aws_user_files_s3_bucket": "amplifyconsolecicddee8dbdd9f893b4815839c4057712143317-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
